language: python
python:
 - '2.7'
 - '3.5'
 - '3.6'
sudo: required
services:
- docker
before_install:
- pip install pytest
install:
- pip install .
script: cd test && py.test
deploy:
  provider: pypi
  user: avirshup
  password:
    secure: n7N6SYWcbQNGe/tKXbEaIXwTlcrRuGoiavYvfiKLEHUOWFa64teuY5tho2hR/Z3MwWceQ3vtXuUw9xUt1WHcK4C2lqBS9I3wiQ31qwwbIcoynIyK37EazsM2mba7Z1HKZIo69KxgWyknGFhqBSUv48KnJPiaDWVi73YzqZJU/NPtjjp+zzubBuDihoMR5WamIm6sS8Wa/QpaJW0rVV9aet9aXzNRMAb9SuF/JotVnHNNos2Ksq4PTiCUC+2WyxfIcOF86znKpb6/MhuF1O+5v7s4KltG6pEg8SI5h3DrqTZIzQab3ueLnxsDqK2VzVBzfcy3wtMySuAmQPNClimub1XKfOWsdeKHbtZ92H1wQa/zYeKeSGmQN8fCbD49LsMEL7RfcVQn6re+WAygSv+63VnYsQG1MsW5EQZIcnoULQ5WRq5NRN/cJu2KPhabhAs/cFih02UjJjQCVI3/j2ZihExcT3PJQkj2JuPWM8VfOOVUD95TdJdYWvfUDTumIuKHxEqRTBYS/aC39c63LhHqmf1zYwEYpgUky8YZwXbT5m5nEqmxVxLM4zP3P0MCjJWI9KWrgUeZSYnZ0b+CUWqwyQckUhmJAK1HPA7SzfZqlkJ0bRy/3mKLFgHOqeTzX3Iq8IuqaRsBe1F3f4YjcB+JzJSOZ6U53QFDLjSFbo/V/NU=
  on:
    tags: true
    repo: avirshup/DockerMake
