language: python
python:
- '2.7'
- '3.5'
- '3.6'
sudo: required
services:
- docker
before_install:
- pip install pytest
install:
- python setup.py sdist
- pip install dist/DockerMake*.tar.gz
script: cd test && py.test
env:
  global:
  - secure: nErzhf1a/OX7wn7ecFtP+amy99THp0SSkm7qT6Tz4UyFyT1wTC0T/Py4N/Wv/U+azY4WArapRhszdvCMx2t8LfpfPIOCpxsPG6juRqhCpSk8lW3tYPD5+899Anwd2CPql4Sbq+BFNT67P4J9OcmQnHPXZ57lE+0CLZ5VoXJuV5OFhrPaPg/vA2AV0KbtK8tz/vZ6ElwP1sv9Yqra2tau2VfEe1SYZER/eAPQTOVLmO1iXz54cAJrVNz1nfwvGouwWeopXIKCI43IUs2q6UaWvfTOLvsx8vodEO9k520s1IbVPYUaMal5L2hkJremBSIjjGfCCRCDVZE64w8gA2Q3fgQwcUJfpycbwP9VlX+3dkQi83/WXJnawhxnXaCG0Ut7dutGfiTH8LOBSZsaS9umOW1Zk9U6Oqxgg8bSX+12tpNW3swphWxhRqMWlh8PEuKfL08FhEVew0M+++f3Hk+rzFIoH1kbNl4s9TU1P0RjNyZoAfp/Hx+/4c07RJ72eRxgq5pd+mIY5Efw5PTDWPXiXhmDtYkZ9PLNolmMMZFT8Ty/kEHjQao9fsLp4NrVtxInNz/OPkNHtj9kSkZLk60MZcCW9E+hCsMYqUO7+MDJdKh35xuqaY9AhS2MGTxs7YVfJ4fBKkMxzAwMVLxzkeT8D/ivRqfVQnT2EevQdbH8mHs=
  - secure: cMay8VLpap0udyZL7xwmKQsen3W7K4fD34GaC1sG+39Kb4vXD9GoMSaGjRz3kd5pQt1TNuVSui2HA9Py0iJWadZghABHgHAdNGoVSI+cdtIDQLLE4DWGcHD/UBpLxEYHMiDdtZ8bgb4sZL5UG43ZZZhf2nQH3VCBmxGIm4h6406rtCzlj7Q4DK7riguwCplaNKUBOwf1vy337W19MDJGkAqTpKmTMXCvjko70xd4RGN+GAhB+1pWxahli+2l8UBhaUnqbGKAq/o0Fqo0UtCcDMxo/MfyBU7OY1L9+SQjZw98aeQOlIyreLmTbhASyy4lCr3VM5ta2rWdv/KYXhi0gkJn7j31jUEhxsV4W44+uX646TKuh0V+VKI6OIUicJjRHrNU1LcDti260VHoihk/A1sF0WTfJ90zRudADm5DJ6KZClBeUmNg1MXSlNDvTOVi3H1IFA7lztpioaahPgMm8NuVx1e+ojNrzHEdeI+WLyk62iAlOaghw/Uj7TY8bFhuu4ZPqMOYZFq9FgYAK2toTPKZeWS2w//9VPeOm/2ucgjavqyzLSkrURanDCV7mrMH9JMEG5mw6IN+vmHCqXz0WvK/dAkzlMFP/WAzJAfCKDO61GMeqVV5TxxaWSSCqjZS4DAD0QRECGUik/1riGv0IMk9xEzfyLUsLiyZYH7VrXg=
